{% set name = "jupyterlab_vim" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vim-{{ version }}.tar.gz
  sha256: 11d850ee91b2864a7b6298aae465219a822f8ccc6e01f23fa03f1ee617afe330

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab >=4.0,<5
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - jupyterlab >=4.0.0,<5

test:
  imports:
    - jupyterlab_vim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-vim
  summary: Code cell vim bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
    - asford
    - fcollonval
    - ianhi
