{% set name = "jupyterlab_vim" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vim-{{ version }}.tar.gz
  sha256: 36ab4495734d90ca5db6ea4ca95cca115c83e9ec1e9d0f36af3ed3a076f74f37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - jupyterlab >=4.0,<5
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - jupyterlab>=4.0.0,<5

test:
  imports:
    - jupyterlab_vim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-vim
  summary: Code cell vim bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
    - asford
    - fcollonval
    - ianhi
