{% set name = "jupyterlab_vim" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_vim-{{ version }}.tar.gz
  sha256: 7ce8141b380ecc65e7297821cc09d46ed2573810d6445438e3ffa154bc50bfd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - hatch-nodejs-version
    - jupyterlab >=4.0.0,<5.0
    - pip
  run:
    - python >=3.8
    - jupyterlab >=4.0.0,<5


test:
  imports:
    - jupyterlab_vim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-vim
  summary: Code cell vim bindings
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - krassowski
    - asford
    - fcollonval
    - ianhi
